### ISSUE TITLE
Programming modes?

### ISSUE THREAD

**Issue by cpitclaudel** [iqbalansari/emacs-emojify#15] opened 2015-12-17 12:34 UTC
This looks great! And it looks great in text-mode.

I've seen the setting to enable emoji in comments and strings in programming modes; could there be a setting to enable it in programming modes outside of comments and strings, too?

**Comment by iqbalansari** [comment] 2015-12-17 15:31
Thanks for the bug report. I believe this a duplicate of #10, as such I am closing it but feel free to reopen if you think this is not a duplicate.

**Closed by iqbalansari** 2015-12-17 15:31 UTC
