### ISSUE TITLE
emoji background doesn't change with faces

### ISSUE THREAD

**Issue by ryanprior** [iqbalansari/emacs-emojify#7] opened 2015-11-15 21:29 UTC
Perhaps we can use transparent images or regenerate with backgrounds for different faces.

![emojify](https://cloud.githubusercontent.com/assets/4389854/11171126/b0372a46-8bad-11e5-9ea5-23cc73d24486.png)
^shows the problem: the blue portion is highlighted because the text is selected, the light gray portion because it's the current line.

**Comment by iqbalansari** [comment] 2015-11-16 16:23
Hi, thanks for the bug report. I think I have a solution for this. Just to properly debug this, what is the theme you are using, the effect is not noticeable in the themes I  use (solarized).

**Comment by ryanprior** [comment] 2015-11-16 16:40
I'm using monokai in the screen shot above. I just tried switching to the 'solarized-dark' and 'tango' themes, both of which seem to have the same issue.

**Comment by iqbalansari** [comment] 2015-11-16 16:43
Actually I meant the effect is not as pronounced as the screenshot above, I agree that it is present. Just pushed a possible fix, could you please try?

**Comment by iqbalansari** [comment] 2015-11-17 04:10
I think that is a problem in the images themselves, I will try to fix this tonight

**Comment by iqbalansari** [comment] 2015-11-22 16:38
This seems to be an issue with images. The images bundled with emojify are resized (24px) versions of the ones from `emoji-one` this was done to mitigate the inability to resize images on Emacsen compiled with no imagemagick support. I tried using original images from `emoji-one` and they look better than the resized ones (though not perfect), have a look

![screenshot from 2015-11-22 22 02 48](https://cloud.githubusercontent.com/assets/2726057/11324901/00432956-9165-11e5-8029-223dd7bf01dd.png)

The first emoji is rendered using the resized version bundled with emojify the second is rendered using the original image from `emoji-one`.

I hope to solve this indirectly by implementing #4 (which I will get to soon) and then  (using your idea of different image sets) allowing users to download unresized images if they prefer.

**Comment by iqbalansari** [comment] 2015-11-22 16:43
On an unrelated note, thanks a lot for all your inputs, much appreciated :smile:. Thanks!

**Comment by ryanprior** [comment] 2015-11-22 17:04
Perhaps we can test for imagemagick support and create pixel-perfect renditions when it's available.

Thank you for putting your effort into creating a great emoji experience in Emacs. You're doing a great job with this package and it's my pleasure to support you.

**Comment by iqbalansari** [comment] 2015-12-02 03:23
Hi,

Just wanted to post an update on this. I initially came up with a specific solution that solved the problem only for emojis in regions that code is in `feature/better-backgrounds` branch, a more general solution for the problem is in `exp/aggressive-bg-face` branch which works for any background face. My only concern is efficiency of updating emoji backgrounds (which I am doing in a `post-command-hook`), on my old laptop Intel Core i3 processor and 4 GB RAM it around 0.000660s - 0.001609s seconds to update backgrounds of visible emoji in the [data/emoji.json](https://github.com/iqbalansari/emacs-emojify/blob/c6de852fcaab6a4982f3148f79838ab3f8781e33/data/emoji.json) file, which I think might be efficient enough. What do you think?

I will be testing it over the week for any bugs or performance issues, if all goes well I will merge this to master.

**Comment by iqbalansari** [comment] 2015-12-05 17:42
Hi @ryanprior,

Did you get a chance to test the branch? I personally haven't come across any regressions and plan to merge `exp/aggressive-bg-face` tomorrow.

**Comment by ryanprior** [comment] 2015-12-05 20:25
I haven't had the chance to test yet. Go ahead and merge, I'll report any bugs I find!

**Comment by iqbalansari** [comment] 2015-12-06 05:48
I have merged the branch to master, hopefully the issues you have mentioned should have been fixed. Could you please try it when MELPA builds and report back?

Thanks

**Comment by ryanprior** [comment] 2015-12-06 06:04
Looks flawless with my brief testing just now. Good fix.

**Comment by iqbalansari** [comment] 2015-12-06 06:34
Thanks for confirming! A lot for credit for this goes to you, I would have not got around to implementing this had you not pushed me :wink:.

I will leave this issue open for sometime before closing it.

**Closed** 2015-12-07 14:25 UTC
Labels: bug, done
