### ISSUE TITLE
Use native emoji when available

### ISSUE THREAD

**Issue by ryanprior** [iqbalansari/emacs-emojify#9] opened 2015-11-22 17:28 UTC
Windows, Android, OSX and iOS all ship with native rendering for Unicode emoji. Support on GNU/Linux [is coming](http://probablement.net/txt/emojilinux).

When native glyphs are available, the default behavior should display emoji as Unicode. We could implement this by providing an `auto` setting for `emojify-display-style` that mimics `image` or `unicode` based on whether the platform [renders native emoji](http://caniemoji.com/).

**Comment by cpitclaudel** [comment] 2015-12-17 12:28
> Windows, Android, OSX and iOS all ship with native rendering for Unicode emoji. Support on GNU/Linux is coming.

The situation is even better, actually: Linux supports it as well, thanks to patches that Google contributed to Freetype.

But the problem is that even when native support is available, Emacs still needs to take advantage of it; which it doesn't, for now, except on MacOS.

I tried launching the topic on emacs-devel, but the reaction was tepid: https://lists.gnu.org/archive/html/emacs-devel/2015-12/msg00713.html

Feel free to voice support there :)

**Comment by iqbalansari** [comment] 2015-12-17 15:49
Is there is a reliable way to detect if a platform supports emojis? One way I can think of is to have a hardcoded list of emoji fonts and check if they are available on the current platform. Do you guys have a better idea?

**Comment by cpitclaudel** [comment] 2015-12-17 16:41
No, a hardcoded list of Emoji fonts won't do: even if Apple Color Emoji or Noto Sans Emoji is available, Emacs on Linux won't use the color glyphs in it. There's no real reliable test, except for the fact that if someone installed this package, they either didn't have color emoji support on their platform, or didn't like the available fonts. For people using the same .emacs on multiple platforms the situation is a bit trickier. Detecting MacOS using `system-type' would work.

**Comment by iqbalansari** [comment] 2016-09-28 13:28
@ryanprior I am closing this for now since there is no way to implement this reliably, please feel free to reopen if you come across a reliable way to achieve this.

Thanks

**Closed by iqbalansari** 2016-09-28 13:28 UTC
Labels: enhancement
