### ISSUE TITLE
When using global-emojify-mode-line-mode in EXWM I can't change workspaces.

### ISSUE THREAD

**Issue by DanGNU** [iqbalansari/emacs-emojify#64] opened 2020-04-07 04:51 UTC
When I activate it during the session or from startup, I get lock in the workspace with the X window open and I'm unable to change to other workspaces, it's necessary to disable the mode to get proper EXWM work.

I use Emacs 27.0.90 and mood-line.

**Comment by iqbalansari** [comment] 2020-04-23 17:21
Hello @DanGNU, thanks for the bug report. This might due to the way mode-line emoji display is implemented currently. Does this happen with vanilla EXWM setup? Would it be possible for you share a minimal config (EXWM and Emacs) to reproduce this?

**Comment by DanGNU** [comment] 2020-04-23 19:43
I use all the defaults in almost all my packages, so `enable-exwm-default` should do. I can test tomorrow again in vanilla Emacs, is there a way I can help debug it or is `debug-on-error` enough?

**Comment by iqbalansari** [comment] 2020-04-26 10:28
I tried reproducing this but could not reproduce it, here is the Emacs configuration I used

```elisp
(require 'package)

(when (< emacs-major-version 27)
  (package-initialize))

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(when (not (and (package-installed-p 'exwm)
		(package-installed-p 'emojify)
		(package-installed-p 'mood-line)))
  (package-refresh-contents)
  (package-install 'exwm)
  (package-install 'emojify)
  (package-install 'mood-line))

(mood-line-mode)

(global-emojify-mode-line-mode +1)
(global-emojify-mode +1)


(require 'exwm)
(require 'exwm-config)
(exwm-config-default)

(global-set-key (kbd "C-x w") #'exwm-workspace-switch)
```
Here are the versions of packages

- Emacs v27.0.91
- Emojify v20200309.553
- EXWM v0.23
- Mood Line v20191101.1955

I am running this via `Xephyr`. Emacs starts up fine and can switch `exwm` workspaces using <kbd>C-x</kbd><kbd>w</kbd>. Can you try if the above works for your setup? If it does there might some other package causing this issue

Thanks

**Comment by DanGNU** [comment] 2020-04-26 10:51
Did you open any X window when testing? Because with only Emacs buffers it works fine.

**Comment by iqbalansari** [comment] 2020-04-26 11:16
Yes I opened, Firefox and Evince in different workspaces and tried switching between the workspaces, it worked as expected

**Comment by DanGNU** [comment] 2020-04-26 12:01
[Here](https://github.com/DanGNU/init-file/blob/master/init.el) is my init file. In [line 256](https://github.com/DanGNU/init-file/blob/b878562071f8a030d9e6d6f86e0640f3a7f923d2/init.el#L256) is EXWM and in [line 314](https://github.com/DanGNU/init-file/blob/b878562071f8a030d9e6d6f86e0640f3a7f923d2/init.el#L314) the emojify configuration. Let me make a new file with what you sent to test it again.

**Comment by DanGNU** [comment] 2020-04-26 12:19
Yes, as soon as I open a X window (yandex, skype or vlc) I can't move to other workplaces, not with `C-x w` nor `s-1, s-2,...`. But as soon as I turned off I can move as usual. This is my system:
```OS: Arch Linux x86_64 
Host: 20255 Lenovo G505s 
Kernel: 5.6.6-arch1-1 
Uptime: 33 mins 
Packages: 606 (pacman) 
Shell: bash 5.0.16 
Resolution: 1366x768 
WM: EXWM: exwm--guide-window 
Theme: Adwaita [GTK2], Adwaita:dark [GTK3] 
Icons: Adwaita [GTK2] 
Terminal: xinit 
CPU: AMD A8-4500M APU (4) @ 1.900GHz 
GPU: AMD ATI Radeon HD 7640G 
Memory: 921MiB / 7158MiB ```

Maybe this can help, because I don't understand the problem.

**Comment by iqbalansari** [comment] 2020-04-26 12:28
Hmm, what happens if trying switching the workspace programmatically? Something like

```
(exwm-workspace-switch 1)
```

**Comment by DanGNU** [comment] 2020-04-26 13:10
If I run that with `M-:` I get
```Debugger entered--Lisp error: (invalid-read-syntax "Trailing garbage following expression")
  read-from-minibuffer("Eval: " nil (keymap (9 . completion-at-point) (27 keymap (9 . completion-at-point)) keymap (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the min...") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuf...") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence "\15" :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (10 . exit-minibuffer) (13 . exit-minibuffer) (7 . minibuffer-keyboard-quit) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-line-or-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-line-or-history-element) (next . next-history-element) (27 keymap (60 . minibuffer-beginning-of-buffer) (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) t read-expression-history)
  read--expression("Eval: ")
  byte-code("\301\302!\303\10!B\207" [current-prefix-arg read--expression "Eval: " eval-expression-get-print-arguments] 3)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)```
But if I change focus to the scratch buffer I can change workplaces. Actually I can't change workplaces only when the X window is the only buffer shown, if I divide the screen with `C-x 2` or `C-x 3` I can change normally.

**Comment by iqbalansari** [comment] 2020-04-26 15:45
I can reproduce the issue now, but will need time to understand why this is happening

**Comment by iqbalansari** [comment] 2020-04-27 06:08
Hello @DanGNU, I have pushed a fix for this on master, could you try it once MELPA updates, thanks!

**Comment by DanGNU** [comment] 2020-04-28 05:41
It works perfectly well now, thank you for taking the time to look through it.

**Comment by iqbalansari** [comment] 2020-04-28 05:44
Thanks for confirming :+1:

**Closed by iqbalansari** 2020-04-28 05:44 UTC
Labels: bug
