### ISSUE TITLE
Failure to download emoji

### ISSUE THREAD

**Issue by arenzana** [iqbalansari/emacs-emojify#49] opened 2019-01-22 01:28 UTC
After installing on emacs 26, if I issue `M-x emojify-mode` and get the following on the minibuffer:

```bash
[emojify] Emoji images not available should I download them now?(yes or no) yes
Connecting to github.com:443...
Wrong type argument: stringp, nil
```
The destination files seem to exist, but it won't download. Any ideas?

**Comment by iqbalansari** [comment] 2019-01-22 04:57
Hi @iarenzana, thanks for the bug report, however downloads seem to be working for me. Can do <kbd>M-x</kbd>`toggle-debug-on-error`<kbd>RET</kbd> and try again, this would give a print a stacktrace when the error happens. Please post the stacktrace here

Thanks

**Comment by iarenzana** [comment] 2019-01-22 15:12
I refreshed the contents and reinstalled and it worked on my mac :)

**Comment by kisik21** [comment] 2019-02-27 17:27
Actually the issue is still present. Here is what I found:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  insert-file-contents(nil nil nil nil nil)
  insert-file-contents-literally(nil)
  emojify--extract-emojis(nil)
  emojify-download-emoji("emojione-v2.2.6-22")
  emojify-download-emoji-maybe()
  emojify-ensure-images()
  emojify-turn-on-emojify-mode()
  emojify-mode(toggle)
  funcall-interactively(emojify-mode toggle)
  call-interactively(emojify-mode record nil)
  command-execute(emojify-mode record)
  execute-extended-command(nil "emojify-mode" nil)
  funcall-interactively(execute-extended-command nil "emojify-mode" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by iqbalansari** [comment] 2019-03-07 07:06
Hi @kisik21, thanks for the stacktrace, this seems like a bug in emojify. Is this happening consistently?

**Comment by kisik21** [comment] 2019-03-09 21:03
Iqbal Ansari <notifications@github.com> writes:
> Hi @kisik21, thanks for the stacktrace, this seems like a bug in emojify. Is this happening consistently?

It does.

**Comment by ivilata** [comment] 2019-03-29 22:35
With `emojify` 1.0, I got the same error. My workaround was downloading the file pointed to by `emojione-v2.2.6-22` in `data/emoji-sets.json` and extract it under `~/.emacs.d/emojis`.

**Comment by iqbalansari** [comment] 2019-05-25 18:29
I cannot reproduce this, I just tried this on Mac and the download worked as expected. I think this might mostly be happening due a failed download, to address that better error reporting has been added for failed downloads, if this error happens consistently, please use [the workaround](https://github.com/iqbalansari/emacs-emojify/issues/49#issuecomment-478169685) suggested by @ivilata. Closing this for now

**Closed by iqbalansari** 2019-05-25 18:29 UTC
Labels: bug
