### ISSUE TITLE
"lisp nesting exceeds maximum depth" when emojify-companytooltips-p non-nil

### ISSUE THREAD

**Issue by titaniumbones** [iqbalansari/emacs-emojify#45] opened 2018-10-27 18:42 UTC
looks like I am getting some kind of loop with the advice being added to `company-pseudo-tooltip-unhide`. When I load company and emojify mode I get the following error. I'm not very good at backtraces but I'm hoping you can read them!

```emacs-lisp
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) nil)
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (display))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) 'display)
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ('display))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (ov 'display))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (overlay-get ov 'display))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((overlay-get ov 'display) (overlay-get ov 'after-string)))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (or (overlay-get ov 'display) (overlay-get ov 'after-string)))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((or (overlay-get ov 'display) (overlay-get ov 'after-string))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (disp (or (overlay-get ov 'display) (overlay-get ov 'after-string))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((disp (or (overlay-get ov 'display) (overlay-get ov 'after-string))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 (1- (length emojified-display)) 'emojified t emojified-display)))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov 'display) (overlay-get ov 'after-string))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 (1- (length emojified-display)) 'emojified t emojified-display)))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov 'display) (overlay-get ov 'after-string))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 (1- (length emojified-display)) 'emojified t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (let* ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov 'display) (overlay-get ov 'after-string))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 (1- (length emojified-display)) 'emojified t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((let* ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov 'display) (overlay-get ov 'after-string))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 (1- ...) 'emojified t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display)))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov 'display) (overlay-get ov 'after-string))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 (1- ...) 'emojified t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display)))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov 'display) (overlay-get ov 'after-string))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 (1- ...) 'emojified t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display)))))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov ...) (overlay-get ov ...))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 ... ... t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display)))) ad-return-value))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((setq ad-return-value (with-no-warnings (funcall ad--addoit-function))) (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov ...) (overlay-get ov ...))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 ... ... t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display)))) ad-return-value))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((ad-return-value) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function))) (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov ...) (overlay-get ov ...))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 ... ... t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display)))) ad-return-value))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (let (ad-return-value) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function))) (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or (overlay-get ov ...) (overlay-get ov ...))) (emojified-display (when disp (emojify-string disp))) (emojified-p (when emojified-display (text-property-any 0 ... ... t emojified-display)))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " 'invisible t)) (overlay-put ov 'after-string emojified-display)))) ad-return-value))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((let (ad-return-value) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function))) (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or ... ...)) (emojified-display (when disp ...)) (emojified-p (when emojified-display ...))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " ... t)) (overlay-put ov 'after-string emojified-display)))) ad-return-value)))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) ((ad--addoit-function &rest ignored) (let (ad-return-value) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function))) (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or ... ...)) (emojified-display (when disp ...)) (emojified-p (when emojified-display ...))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " ... t)) (overlay-put ov 'after-string emojified-display)))) ad-return-value)))
  ad-substitute-tree(#f(compiled-function (form) #<bytecode 0x108ba55>) #f(compiled-function (form) #<bytecode 0x2224b71>) (lambda (ad--addoit-function &rest ignored) (let (ad-return-value) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function))) (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or ... ...)) (emojified-display (when disp ...)) (emojified-p (when emojified-display ...))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " ... t)) (overlay-put ov 'after-string emojified-display)))) ad-return-value)))
  ad-insert-argument-access-forms((lambda (ad--addoit-function &rest ignored) (let (ad-return-value) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function))) (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp (or ... ...)) (emojified-display (when disp ...)) (emojified-p (when emojified-display ...))) (when (and disp emojified-p) (overlay-put ov 'after-string nil) (overlay-put ov 'display (propertize " " ... t)) (overlay-put ov 'after-string emojified-display)))) ad-return-value)) (&rest ignored))
  ad-assemble-advised-definition((&rest ignored) nil nil (funcall ad--addoit-function) nil nil ((emojify-display-emojis-in-company-tooltip nil t (advice lambda (&rest ignored) "Advice to display emojis in company mode tooltips...." (when (and emojify-mode emojify-company-tooltips-p (overlayp (bound-and-true-p company-pseudo-tooltip-overlay))) (let* ((ov company-pseudo-tooltip-overlay) (disp ...) (emojified-display ...) (emojified-p ...)) (when (and disp emojified-p) (overlay-put ov ... nil) (overlay-put ov ... ...) (overlay-put ov ... emojified-display))))))))
  ad-make-advised-definition(company-pseudo-tooltip-unhide)
  ad-activate-advised-definition(company-pseudo-tooltip-unhide nil)
  ad-activate-internal(company-pseudo-tooltip-unhide)
  ad--defalias-fset(nil company-pseudo-tooltip-unhide #f(advice-wrapper :around #f(compiled-function () #<bytecode 0x25a20b1>) ad-Advice-company-pseudo-tooltip-unhide))
  apply(ad--defalias-fset nil (company-pseudo-tooltip-unhide #f(advice-wrapper :around #f(compiled-function () #<bytecode 0x25a20b1>) ad-Advice-company-pseudo-tooltip-unhide)))
  #f(advice-wrapper :around nil ad--defalias-fset)(company-pseudo-tooltip-unhide #f(advice-wrapper :around #f(compiled-function () #<bytecode 0x25a20b1>) ad-Advice-company-pseudo-tooltip-unhide))
  advice--defalias-fset(#f(advice-wrapper :around nil ad--defalias-fset) company-pseudo-tooltip-unhide #f(compiled-function () #<bytecode 0x25a20b1>))
  apply(advice--defalias-fset #f(advice-wrapper :around nil ad--defalias-fset) (company-pseudo-tooltip-unhide #f(compiled-function () #<bytecode 0x25a20b1>)))
  #f(advice-wrapper :around #f(advice-wrapper :around nil ad--defalias-fset) advice--defalias-fset)(company-pseudo-tooltip-unhide #f(compiled-function () #<bytecode 0x25a20b1>))
  defalias(company-pseudo-tooltip-unhide #f(compiled-function () #<bytecode 0x25a20b1>))
  company()
  run-hooks(global-company-mode-hook global-company-mode-on-hook)
```

**Comment by titaniumbones** [comment] 2018-11-13 05:19
I'm just noticing this again as I run through my config. Any hints? I'm bummed to deactivate emojify in company tooltips - -sigh!

**Comment by iqbalansari** [comment] 2018-12-27 06:55
Hi @titaniumbones, sorry the late response.

 Is this the entire stack trace? What is the value of the variable `max-lisp-eval-depth`? The default value for the variable is 800, the trace you have posted is really small to trigger the error

**Comment by iqbalansari** [comment] 2019-05-25 03:27
Hi @titaniumbones, I am closing this for now, since I am not able to reproduce it, feel free to re-open if this happens again

**Closed by iqbalansari** 2019-05-25 03:27 UTC
Labels: bug
