### ISSUE TITLE
Infinite loop where interactive but unable to answer

### ISSUE THREAD

**Issue by tagd** [iqbalansari/emacs-emojify#100] opened 2022-01-31 03:37 UTC
When running Doom emacs emojify creates a 'max-lisp-eval-depth' error with the [emojify--confirm-emoji-download](
https://github.com/iqbalansari/emacs-emojify/blob/1b726412f19896abf5e4857d4c32220e33400b55/emojify.el#L1482) function as it repeatedly asks if it should download emoji's.  As doom inits emojify with a hook, see [here](https://github.com/hlissner/doom-emacs/blob/master/modules/ui/emoji/config.el), by default it doesn't answer `yes-or-no-p`, so the question is repeated until max eval depth is hit.

This issue can be fixed in doom by adding `(setq emojify-download-emojis-p t)` to config.  Figured I should raise it here so the next person with the issue can find an answer 😊

**Comment by feluxe** [comment] 2022-05-10 13:53
I was effected just now. Thanks for posting the solution!

**Comment by hlissner** [comment] 2022-10-01 15:19
This was caused by a bug in Doom's core (and should've been reported there, considering you had identified the cause). In any case, it was fixed in https://github.com/doomemacs/doomemacs/commit/a6f0bf3123102f54fdb9852a38ee2a3b47d5f80a, so this issue can be closed.

**Closed as completed** 2022-10-01 21:18 UTC
